### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by pveber**
I'm preparing a dunified version of your library, and with stricter compilation options there were a few warnings that are corrected in the present PR.

### CODE REVIEW

**Comment by cyril-allignol** [comment]
Thank you for your interest and your corrections. Before I merge: is there a reason why you handled print_point and print_bbox differently? Both were debugging functions, I did not export them at first because I didn't see the use; you choose to export one but remove the other.

**Comment by pveber** [comment]
Actually it was a pretty arbitrary decision: I just noticed that `print_point` took float arrays, while points were represented by dedicated types. So I thought this function had been written at a time points were represented by arrays and that maybe it would not be useful anymore. I can add a commit to reinstate the function, no problem.

**Comment by cyril-allignol** [comment]
Hm, my mistake, I checked too fast... I'll merge your fixes as proposed.

**Comment by pveber** [comment]
great, thanks!

**Pull request merged**
